1 Devuelve los IRIs de los edificios y sus respectivos distritos. 
PREFIX our: <http://www.consumo_madrid.com/ontology#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT DISTINCT ?x ?y
WHERE {?z a our:Building
	?z our:buildingName ?x.
       ?t a our:District.
	?x our:isIn ?t
	?t owl:sameAs ?y.
	}

2 Devuelve los Data Properties y Object Properties de la clase Building.
PREFIX our: <http://www.consumo_madrid.com/ontology#>.
SELECT DISTINCT ?x
WHERE	{?y a our:Building
	 ?y ?x ?z.
		}

3 Cuenta el número de edificios.
PREFIX our: <http://www.consumo_madrid.com/ontology#>
SELECT COUNT DISTINCT ?x
WHERE	{?x a our:Building 
	}

4 Obtiene todas las clases.
PREFIX rr: <http://www.w3.org/ns/r2rml#>
SELECT DISTINCT ?Class
WHERE	{?Class a rr:Class
	}