# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hSv61ejXESrp34CUz1PqZCsoA43tzc8y

**Task 06: Modifying RDF(s)**
"""

from rdflib import Graph, Namespace, Literal, XSD
from rdflib.namespace import RDF, RDFS


github_storage = "https://raw.githubusercontent.com/AndreaCimminoArriaga/LinkedData2021-2022/main/Assignment4/"

"""Leemos el fichero RDF de la forma que lo hemos venido haciendo"""
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage + "/resources/example5.rdf", format="xml")

print("""Create a new class named Researcher""")

NS = Namespace("http://somewhere#")
g.add((NS.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
    print(s, p, o)

print('\n**TASK 6.1: Create a new class named "University"**')
print(NS.University, RDF.type, RDFS.Class)
g.add((NS.University, RDF.type, RDFS.Class))

print('\n**TASK 6.2: Add "Researcher" as a subclass of "Person"**')
print(NS.Researcher, RDFS.subClassOf, NS.Person)
g.add((NS.Researcher, RDFS.subClassOf, NS.Person))

print('\n**TASK 6.3: Create a new individual of Researcher named "Jane Smith"**')
print(NS.JaneSmith, RDF.type, NS.Researcher)

g.add((NS.JaneSmith, RDF.type, NS.Researcher))

print('\n**TASK 6.4: Add to the individual JaneSmith the fullName, given and family names**')
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")

print(NS.JaneSmith, VCARD.FN, Literal("Jane Smith", datatype=XSD.string))
print(NS.JaneSmith, VCARD.Family, Literal("Smith", datatype=XSD.string))
print(NS.JaneSmith, VCARD.Given, Literal("Jane", datatype=XSD.string))

g.add((NS.JaneSmith, VCARD.FN, Literal("Jane Smith", datatype=XSD.string)))
g.add((NS.JaneSmith, VCARD.Family, Literal("Smith", datatype=XSD.string)))
g.add((NS.JaneSmith, VCARD.Given, Literal("Jane", datatype=XSD.string)))


print('\n**TASK 6.5: Add UPM as the university where John Smith works**')
print(NS.UPM, RDF.type, NS.University)
print(NS.JohnSmith, NS.Works, NS.UPM)

g.add((NS.UPM, RDF.type, NS.University))
g.add((NS.JohnSmith, NS.Works, NS.UPM))
