# -*- coding: utf-8 -*-
"""Task08.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mimmRhJ7s4VDivs7omfqoWZ2MEQtFfNK

**Task 08: Completing missing data**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/AndreaCimminoArriaga/LinkedData2021-2022/main/Assignment4/"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g1.parse(github_storage+"resources/data01.rdf", format="xml")
g2.parse(github_storage+"resources/data02.rdf", format="xml")

"""Tarea: lista todos los elementos de la clase Person en el primer grafo (data01.rdf) y completa los campos (given name, family name y email) que puedan faltar con los datos del segundo grafo (data02.rdf). Puedes usar consultas SPARQL o iterar el grafo, o ambas cosas."""

NS = Namespace("http://somewhere#")
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
A = Namespace("http://data.org#")
from rdflib.namespace import RDF, RDFS

from rdflib.plugins.sparql import prepareQuery

#Devuelvo los lementos de la clase Person
q1 = prepareQuery('''
  SELECT 
    ?Elementos
	WHERE { 
        ?Elementos rdf:type a:Person.
  } 
  ''',
  initNs = { "ns": NS, "rdf": RDF, "a":A}
)

for r in g1.query(q1):
  print(r)

# Creamos un grafo con los datos de g1 y lo rellenamos con g2
graph = g1 + g2
print(graph.serialize(format="turtle"))