# -*- coding: utf-8 -*-
"""Task09.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FZYAcSZjFVPTmd9ZGJ1ZGNgOeUrqjVS5

**Task 09: Data linking**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/AndreaCimminoArriaga/LinkedData2021-2022/main/Assignment4/"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g3 = Graph()
g1.parse(github_storage+"resources/data03.rdf", format="xml")
g2.parse(github_storage+"resources/data04.rdf", format="xml")

"""Busca individuos en los dos grafos y enlázalos mediante la propiedad OWL:sameAs, inserta estas coincidencias en g3. Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia. Ten en cuenta que las URI no tienen por qué ser iguales para un mismo individuo en los dos grafos."""

NS = Namespace("http://somewhere#")
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
A = Namespace("http://data.three.org#")
OWL = Namespace("http://www.w3.org/TR/owl-ref/")

for s1,p1,o1 in g1.triples((None, VCARD.Family, None)):
  for s2,p2,o2 in g2.triples((None, VCARD.Family, None)):
    if o1 == o2:
      for s3,p3,o3 in g1.triples((s1, VCARD.Given, None)):
        for s4,p4,o4 in g2.triples((s2, VCARD.Given, None)):
          if o3 == o4:
            #Añado las coincidencias en g3 bajo la propieded OWL.sameAs
            g3.add((s1, OWL.sameAs, s2))

print(g3.serialize(format="ttl"))

'''
Para comprobar que el resultado anterior es cierto,
analizo los grafos. Observo que solo deben coincidir 
en Sara Jones(0001) y John Doe(0005)
'''
print(g1.serialize(format="ttl"))
print(g2.serialize(format="ttl"))